# Generated by Django 5.0.3 on 2024-07-04 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_raiting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Raiting',
            new_name='Rating',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='rate',
        ),
    ]
