# Generated by Django 5.0.3 on 2024-07-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(default='https://upload.wikimedia.org/wikipedia/commons/7/72/Default-welcomer.png', max_length=255),
        ),
    ]
